#---------------------------------#
#      appveyor.com config        #
#---------------------------------#


build_script:
  - ps: .\CreatePackages.ps1 -nugetApiKey Env:\NUGET_API_KEY -CommitLocalGit -PushGit -PublishNuget
